version: '3.8'

services:
  # 1. FastAPI 애플리케이션 서비스
  web:
    build: .
    restart: always
    command: /bin/bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app # 로컬 변경 사항을 즉시 반영
    ports:
      - "8000:8000"
    env_file:
      - .env # 환경 변수 파일 로드
    environment:
      - PYTHONPATH=/usr/src/app
      - DEBUG=True
    #  - DATABASE_URL=mysql+pymysql://{self.MYSQL_USER}:{self.MYSQL_PASSWORD}@{self.MYSQL_HOST}/{self.MYSQL_DATABASE}?client_flag=2


  # 2. MySQL 데이터베이스 서비스
  db:
    image: mysql:8.0
    container_name: uoms_mysql
    env_file:
      - .env
    environment:
      # .env에 설정된 변수를 MySQL에서 인식하도록 매핑
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # 데이터 영속성 유지
      # 로컬의 init.sql 파일을 컨테이너의 초기화 디렉토리에 마운트
      - ./grant_remote_access.sh:/docker-entrypoint-initdb.d/grant_remote_access.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "3307:3306"

volumes:
  db_data: